env:
  browser: true
  commonjs: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  semi-style:
    - error
    - last
  semi-spacing:
    - error
  comma-spacing:
    - error
  func-call-spacing:
    - error
  key-spacing:
    - error
  keyword-spacing:
    - error
  space-before-blocks:
    - error
  space-in-parens:
    - error
  space-infix-ops:
    - error
  camelcase:
    - warn
